import React, { Component } from 'react';

class BestPokemonList extends Component {
  render() {
    return(
      <div>
        <p>DLCなし</p>
        <div>
          <table>
            <tr>
              <th>名前</th><th>タイプ</th>
            </tr>
            <tr>
              <td>タチフサグマ</td><td>ノーマル、あく</td>
            </tr>
            <tr>
              <td>ヤレユータン</td><td>ノーマル、エスパー</td>
            </tr>
            <tr>
              <td>カビゴン</td><td>ノーマル</td>
            </tr>
            <tr>
              <td>チラチーノ</td><td>ノーマル</td>
            </tr>
            <tr>
              <td>バイウールー</td><td>ノーマル</td>
            </tr>
            <tr>
              <td>ジジーロン</td><td>ノーマル、ドラゴン</td>
            </tr>
          </table>
        </div>

        <div>
          <table>
            <tr>
              <th>名前</th><th>タイプ</th>
            </tr>
            <tr>
              <td>エルフーン</td><td>くさ、フェアリー</td>
            </tr>
            <tr>
              <td>ルンパッパ</td><td>くさ、みず</td>
            </tr>
            <tr>
              <td>リーフィア</td><td>くさ</td>
            </tr>
            <tr>
              <td>ロトム</td><td>くさ、でんき</td>
            </tr>
            <tr>
              <td>ナットレイ</td><td>くさ、はがね</td>
            </tr>
            <tr>
              <td>ロズレイド</td><td>くさ、どく</td>
            </tr>
          </table>
        </div>

        <div>
          <table>
            <tr>
              <th>名前</th><th>タイプ</th>
            </tr>
            <tr>
              <td>カマスジョー</td><td>みず</td>
            </tr>
            <tr>
              <td>ドヒドイデ</td><td>みず、どく</td>
            </tr>
            <tr>
              <td>パルシェン</td><td>みず、こおり</td>
            </tr>
            <tr>
              <td>トリトドン</td><td>みず、じめん</td>
            </tr>
            <tr>
              <td>ミロカロス</td><td>みず</td>
            </tr>
            <tr>
              <td>グソクムシャ</td><td>みず、むし</td>
            </tr>
          </table>
        </div>

        <div>
          <table>
            <tr>
              <th>名前</th><th>タイプ</th>
            </tr>
            <tr>
              <td>エンニュート</td><td>ほのお、どく</td>
            </tr>
            <tr>
              <td>ウインディ</td><td>ほのお</td>
            </tr>
            <tr>
              <td>ブースター</td><td>ほのお</td>
            </tr>
            <tr>
              <td>シャンデラ</td><td>ほのお、ゴースト</td>
            </tr>
            <tr>
              <td>セキタンザン</td><td>ほのお、いわ</td>
            </tr>
            <tr>
              <td>ロトム</td><td>ほのお、でんき</td>
            </tr>
          </table>
        </div>

        <div>
          <table>
            <tr>
              <th>名前</th><th>タイプ</th>
            </tr>
            <tr>
              <td>ドラパルト</td><td>ゴースト、ドラゴン</td>
            </tr>
            <tr>
              <td>ゲンガー</td><td>ゴースト、どく</td>
            </tr>
            <tr>
              <td>デスカーン</td><td>ゴースト</td>
            </tr>
            <tr>
              <td>ギルガルド</td><td>ゴースト、はがね</td>
            </tr>
            <tr>
              <td>ヨノワール</td><td>ゴースト</td>
            </tr>
            <tr>
              <td>ヤミラミ</td><td>ゴースト、あく</td>
            </tr>
          </table>
        </div>

        <div>
          <table>
            <tr>
              <th>名前</th><th>タイプ</th>
            </tr>
            <tr>
              <td>ドータクン</td><td>エスパー、はがね</td>
            </tr>
            <tr>
              <td>イオルブ</td><td>エスパー、むし</td>
            </tr>
            <tr>
              <td>ネンドール</td><td>エスパー、じめん</td>
            </tr>
            <tr>
              <td>ブリムオン</td><td>エスパー</td>
            </tr>
            <tr>
              <td>エルレイド</td><td>エスパー、かくとう</td>
            </tr>
            <tr>
              <td>カラマネロ</td><td>エスパー、あく</td>
            </tr>
          </table>
        </div>

        <div>
          <table>
            <tr>
              <th>名前</th><th>タイプ</th>
            </tr>
            <tr>
              <td>バンギラス</td><td>いわ、あく</td>
            </tr>
            <tr>
              <td>ズルズキン</td><td>あく、かくとう</td>
            </tr>
            <tr>
              <td>ブラッキー</td><td>あく</td>
            </tr>
            <tr>
              <td>サザンドラ</td><td>あく、ドラゴン</td>
            </tr>
            <tr>
              <td>タチフサグマ</td><td>あく</td>
            </tr>
            <tr>
              <td>ドラピオン</td><td>あく、どく</td>
            </tr>
          </table>
        </div>

        <div>
          <table>
            <tr>
              <th>名前</th><th>タイプ</th>
            </tr>
            <tr>
              <td>トゲキッス</td><td>フェアリー、ひこう</td>
            </tr>
            <tr>
              <td>ブリムオン</td><td>フェアリー、エスパー</td>
            </tr>
            <tr>
              <td>ガラルギャロップ</td><td>フェアリー、エスパ＝</td>
            </tr>
            <tr>
              <td>ミミッキュ</td><td>フェアリー、ゴースト</td>
            </tr>
            <tr>
              <td>オーロンゲ</td><td>フェアリー、あく</td>
            </tr>
            <tr>
              <td>フレフワン</td><td>フェアリー</td>
            </tr>
          </table>
        </div>

        <div>
          <table>
            <tr>
              <th>名前</th><th>タイプ</th>
            </tr>
            <tr>
              <td>ロトム</td><td>でんき、こおり</td>
            </tr>
            <tr>
              <td>グレイシア</td><td>こおり</td>
            </tr>
            <tr>
              <td>ユキメノコ</td><td>こおり、ゴースト</td>
            </tr>
            <tr>
              <td>ラプラス</td><td>こおり、みず</td>
            </tr>
            <tr>
              <td>マンムー</td><td>こおり、じめん</td>
            </tr>
            <tr>
              <td>バイバニラ</td><td>こおり</td>
            </tr>
          </table>
        </div>

        <div>
          <table>
            <tr>
              <th>名前</th><th>タイプ</th>
            </tr>
            <tr>
              <td>ツボツボ</td><td>むし、いわ</td>
            </tr>
            <tr>
              <td>グソクムシャ</td><td>むし、みず</td>
            </tr>
            <tr>
              <td>イオルブ</td><td>むし、エスパー</td>
            </tr>
            <tr>
              <td>アギルダー</td><td>むし</td>
            </tr>
            <tr>
              <td>シュバルゴ</td><td>むし、はがね</td>
            </tr>
            <tr>
              <td>アイアント</td><td>むし、はがね</td>
            </tr>
          </table>
        </div>
      </div>
    );
  }
}

export default BestPokemonList;